from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import QDir
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 654)
        MainWindow.setStyleSheet("background-color: rgb(27, 72, 127);\n"
"alternate-background-color: rgb(108, 179, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 1161, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 0, 181, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.fileDropFilterLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.fileDropFilterLayout.setContentsMargins(0, 0, 0, 0)
        self.fileDropFilterLayout.setObjectName("fileDropFilterLayout")
        self.fileDropFilter = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fileDropFilter.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileDropFilter.setObjectName("fileDropFilter")
        # Populate drive letters in fileDropFilter
        self.populateDriveList(self.fileDropFilter)
        self.fileDropFilter.currentIndexChanged.connect(self.updateTreeView)
        self.fileDropFilterLayout.addWidget(self.fileDropFilter)

        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(220, 70, 311, 471))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.fileDropdownLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.fileDropdownLayout_3.setContentsMargins(0, 0, 0, 0)
        self.fileDropdownLayout_3.setObjectName("fileDropdownLayout_3")
        self.listView_3 = QtWidgets.QListView(self.verticalLayoutWidget_7)
        self.listView_3.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.listView_3.setObjectName("listView_3")
        self.fileDropdownLayout_3.addWidget(self.listView_3)
        
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 70, 181, 461))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.fileLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.fileLayout_3.setContentsMargins(0, 0, 0, 0)
        self.fileLayout_3.setObjectName("fileLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.horizontalLayoutWidget_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 177, 387))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.fileTreeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_7)
        self.fileTreeView.setGeometry(QtCore.QRect(0, 0, 181, 461))
        self.fileTreeView.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileTreeView.setObjectName("fileTreeView")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_7)
        self.fileLayout_3.addWidget(self.scrollArea_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(650, 70, 271, 281))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.imageLabel_2.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.imageLabel_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.imageLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageLabel_2.setText("")
        self.imageLabel_2.setObjectName("imageLabel_2")
        self.horizontalLayout_3.addWidget(self.imageLabel_2)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(220, 0, 231, 61))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.fileSearchLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.fileSearchLayout_2.setContentsMargins(0, 0, 0, 0)
        self.fileSearchLayout_2.setObjectName("fileSearchLayout_2")
        self.fileSearch_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.fileSearch_2.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileSearch_2.setObjectName("fileSearch_2")
        self.fileSearchLayout_2.addWidget(self.fileSearch_2)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(730, 360, 111, 41))
        self.label_2.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(550, 70, 71, 211))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.fileFilterLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.fileFilterLayout_2.setContentsMargins(0, 0, 0, 0)
        self.fileFilterLayout_2.setObjectName("fileFilterLayout_2")
        self.extFilterButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.extFilterButton_2.setObjectName("extFilterButton_2")
        self.fileFilterLayout_2.addWidget(self.extFilterButton_2)
        self.nameFilterButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.nameFilterButton_2.setObjectName("nameFilterButton_2")
        self.fileFilterLayout_2.addWidget(self.nameFilterButton_2)
        self.dateFilterButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.dateFilterButton_2.setObjectName("dateFilterButton_2")
        self.fileFilterLayout_2.addWidget(self.dateFilterButton_2)
        self.fileRenameButton = QtWidgets.QPushButton(self.tab)
        self.fileRenameButton.setGeometry(QtCore.QRect(740, 410, 81, 41))
        self.fileRenameButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.fileRenameButton.setObjectName("fileRenameButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.copyButton = QtWidgets.QPushButton(self.tab_2)
        self.copyButton.setGeometry(QtCore.QRect(980, 410, 81, 41))
        self.copyButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(870, 70, 271, 281))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.imageLabel.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.imageLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.imageLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_2.addWidget(self.imageLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(550, 70, 311, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.fileDropdownLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.fileDropdownLayout_2.setContentsMargins(0, 0, 0, 0)
        self.fileDropdownLayout_2.setObjectName("fileDropdownLayout_2")
        self.listView_2 = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.listView_2.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.listView_2.setObjectName("listView_2")
        self.fileDropdownLayout_2.addWidget(self.listView_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 181, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fileLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.fileLayout.setContentsMargins(0, 0, 0, 0)
        self.fileLayout.setObjectName("fileLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 177, 457))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.fileTreeView_2 = QtWidgets.QTreeView(self.scrollAreaWidgetContents_2)
        self.fileTreeView_2.setGeometry(QtCore.QRect(0, 0, 181, 461))
        self.fileTreeView_2.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileTreeView_2.setObjectName("fileTreeView_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.fileLayout.addWidget(self.scrollArea)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(960, 360, 111, 41))
        self.label.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 0, 231, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.fileSearchLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.fileSearchLayout.setContentsMargins(0, 0, 0, 0)
        self.fileSearchLayout.setObjectName("fileSearchLayout")
        self.fileSearch = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.fileSearch.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileSearch.setObjectName("fileSearch")
        self.fileSearchLayout.addWidget(self.fileSearch)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 70, 311, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.fileDropdownLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.fileDropdownLayout.setContentsMargins(0, 0, 0, 0)
        self.fileDropdownLayout.setObjectName("fileDropdownLayout")
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setStyleSheet("background-color: rgb(20, 54, 95);")
        self.listView.setObjectName("listView")
        self.fileDropdownLayout.addWidget(self.listView)

        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 0, 181, 61))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.fileDropFilterLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.fileDropFilterLayout_2.setContentsMargins(0, 0, 0, 0)
        self.fileDropFilterLayout_2.setObjectName("fileDropFilterLayout_2")
        self.fileDropFilter_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.fileDropFilter_2.setStyleSheet("background-color: rgb(245, 255, 207);")
        self.fileDropFilter_2.setObjectName("fileDropFilter_2")
        # Populate drive letters in fileDropFilter_2
        self.populateDriveList(self.fileDropFilter_2)
        self.fileDropFilter_2.currentIndexChanged.connect(self.updateTreeView_2)
        self.fileDropFilterLayout_2.addWidget(self.fileDropFilter_2)

        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(470, 10, 301, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.fileFilterLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.fileFilterLayout.setContentsMargins(0, 0, 0, 0)
        self.fileFilterLayout.setObjectName("fileFilterLayout")
        self.fileZipButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.fileZipButton.setObjectName("fileZipButton")
        self.fileFilterLayout.addWidget(self.fileZipButton)
        self.nameFilterButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.nameFilterButton.setObjectName("nameFilterButton")
        self.fileFilterLayout.addWidget(self.nameFilterButton)
        self.extFilterButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.extFilterButton.setObjectName("extFilterButton")
        self.fileFilterLayout.addWidget(self.extFilterButton)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExFiles"))
        self.label_2.setText(_translate("MainWindow", "FileName.txt"))
        self.extFilterButton_2.setText(_translate("MainWindow", "Extension"))
        self.nameFilterButton_2.setText(_translate("MainWindow", "Name"))
        self.dateFilterButton_2.setText(_translate("MainWindow", "Date"))
        self.fileRenameButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "File View"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.label.setText(_translate("MainWindow", "FileName.txt"))
        self.fileZipButton.setText(_translate("MainWindow", "ZIP"))
        self.nameFilterButton.setText(_translate("MainWindow", "Name"))
        self.extFilterButton.setText(_translate("MainWindow", "Extension"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "File Copy"))

    def populateDriveList(self, comboBox):
        import string
        from PyQt5.QtCore import QDir
        
        drives = ['%s:' % d for d in string.ascii_uppercase if QDir.root().exists('%s:' % d)]
        
        for drive in drives:
            comboBox.addItem(drive)

    def updateTreeView(self, index):
        drive = self.fileDropFilter.itemText(index)
        model = QtWidgets.QFileSystemModel()
        model.setRootPath(drive)
        self.fileTreeView.setModel(model)
        self.fileTreeView.setRootIndex(model.index(drive))

    def updateTreeView_2(self, index):
        drive = self.fileDropFilter_2.itemText(index)
        model = QtWidgets.QFileSystemModel()
        model.setRootPath(drive)
        self.fileTreeView_2.setModel(model)
        self.fileTreeView_2.setRootIndex(model.index(drive))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
